export default function PrivacyPolicy() {
    return (
        <div className="max-w-4xl mx-auto p-6 bg-white">
            <h1 className="text-3xl font-bold text-black mb-6 text-center">Privacy Policy</h1>
            
            <div className="space-y-6">
                <p className="text-gray-700 leading-relaxed">
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>

                <p className="text-gray-700">
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>

                <h2 className="text-2xl text-black font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
                
                <h3 className="text-xl font-semibold text-black mb-3">Interpretation</h3>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li>The words of which the initial letter is capitalized have meanings defined under the following conditions</li>
                    <li>The following definitions shall have the same meaning regardless of whether they appear in singular or in plural</li>
                </ul>

                <h3 className="text-xl text-black font-semibold mb-3 mt-6">Definitions</h3>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Exameets Skillverse Academy</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority</li>
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service</li>
                    <li><strong>Website</strong> refers to skillverse.exameets.in, accessible from skillverse.exameets.in</li>
                    <li><strong>Service</strong> refers to the Website</li>
                    <li><strong>Country</strong> refers to: Andhra Pradesh, India</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service</li>
                    <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 text-black mb-4">Collecting and Using Your Personal Data</h2>
                
                <h3 className="text-xl font-semibold mb-3 text-black">Types of Data Collected</h3>
                
                <h4 className="text-lg font-medium text-black mb-2">Personal Data</h4>
                <p className="text-gray-700 mb-3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-4">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Usage Data</li>
                </ul>

                <h4 className="text-lg font-medium text-black mb-2">Usage Data</h4>
                <p className="text-gray-700 mb-3">Usage Data is collected automatically when using the Service.</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data</li>
                    <li>When You access the Service by or through a mobile device, We may collect certain information automatically, including the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data</li>
                    <li>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device</li>
                </ul>

                <h3 className="text-xl font-semibold mb-3 text-black mt-6">Tracking Technologies and Cookies</h3>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information</li>
                    <li>Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service</li>
                    <li>You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service</li>
                    <li>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser</li>
                </ul>

                <h4 className="text-lg text-black font-medium mb-2 mt-4">Types of Cookies We Use:</h4>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li><strong>Necessary / Essential Cookies:</strong> Type: Session Cookies. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features</li>
                    <li><strong>Cookies Policy / Notice Acceptance Cookies:</strong> Type: Persistent Cookies. Purpose: These Cookies identify if users have accepted the use of cookies on the Website</li>
                    <li><strong>Functionality Cookies:</strong> Type: Persistent Cookies. Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference</li>
                </ul>

                <h2 className="text-2xl text-black font-semibold mt-8 mb-4">Use of Your Personal Data</h2>
                <p className="text-gray-700 mb-3">The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service</li>
                    <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased</li>
                    <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications</li>
                    <li><strong>To provide You with news:</strong> special offers and general information about other goods, services and events which we offer</li>
                    <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us</li>
                </ul>

                <h3 className="text-xl font-semibold mb-3 text-black mt-6">Sharing Your Personal Information</h3>
                <p className="text-gray-700 mb-3">We may share your personal information in the following situations:</p>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service</li>
                    <li><strong>For Business transfers:</strong> We may share or transfer Your personal information in connection with any merger, sale of Company assets, financing, or acquisition</li>
                    <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy</li>
                    <li><strong>With Business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions</li>
                    <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users</li>
                </ul>

                <h2 className="text-2xl font-semibold text-black mt-8 mb-4">Retention of Your Personal Data</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy</li>
                    <li>We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies</li>
                    <li>The Company will also retain Usage Data for internal analysis purposes</li>
                    <li>Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 text-black mb-4">Transfer of Your Personal Data</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located</li>
                    <li>This information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction</li>
                    <li>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer</li>
                    <li>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy</li>
                </ul>

                <h2 className="text-2xl font-semibold text-black mt-8 mb-4">Disclosure of Your Personal Data</h2>
                
                <h3 className="text-xl font-semibold text-black mb-3">Business Transactions</h3>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred</li>
                    <li>We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy</li>
                </ul>

                <h3 className="text-xl font-semibold mb-3 text-black mt-6">Law Enforcement</h3>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities</li>
                </ul>

                <h3 className="text-xl font-semibold mb-3 text-black mt-6">Other Legal Requirements</h3>
                <p className="text-gray-700 mb-3">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul className="list-disc pl-6 space-y-2 text-gray-700">
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 text-black mb-4">Security of Your Personal Data</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure</li>
                    <li>While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 text-black mb-4">Children's Privacy</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13</li>
                    <li>If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us</li>
                    <li>If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers</li>
                    <li>We also may limit how We collect, use, and store some of the information of Users between 13 and 18 years old</li>
                    <li>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information</li>
                </ul>

                <h2 className="text-2xl font-semibold text-black mt-8 mb-4">Links to Other Websites</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>Our Service may contain links to other websites that are not operated by Us</li>
                    <li>If You click on a third party link, You will be directed to that third party's site</li>
                    <li>We strongly advise You to review the Privacy Policy of every site You visit</li>
                    <li>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services</li>
                </ul>

                <h2 className="text-2xl font-semibold mt-8 text-black mb-4">Changes to this Privacy Policy</h2>
                <ul className="list-disc pl-6 space-y-3 text-gray-700">
                    <li>We may update our Privacy Policy from time to time</li>
                    <li>We will notify You of any changes by posting the new Privacy Policy on this page</li>
                    <li>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective</li>
                    <li>You are advised to review this Privacy Policy periodically for any changes</li>
                    <li>Changes to this Privacy Policy are effective when they are posted on this page</li>
                </ul>

                <div className="mt-8 p-4 bg-gray-100 rounded-lg">
                    <p className="text-gray-800 font-medium text-center">
                        By using our Service, you acknowledge that you have read and understood this Privacy Policy.
                    </p>
                </div>
            </div>
        </div>
    );
}
